### ISSUE TITLE
README updaten

### ISSUE THREAD

**Issue by Xenon27** [Xenon27/coc-loyalty-ranking#15]
AC:
- What is required to run
- env
- What does it do

**Comment by flowolfmolf** [comment]
@Xenon27 theoretisch kann man darunter noch "Visit running site" oder sowas machen, wo die domain nommal verlinkt wird

**Comment by Xenon27** [comment]
@flowolfmolf willst du das noch hinzu machen? 👍 😄

**Comment by flowolfmolf** [comment]
@Xenon27 kann ich erst morgen
KB meinen Geschäftslaptop jz zu booten und au net wegen der letzten Woche das Projekt nommal auf meinen neuen privat Rechner zu klonen xD
Machs morgen vor Datenbanken

**Comment by Xenon27** [comment]
@flowolfmolf dann gucken wir das morgen nochmal zusammen drauf
